apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-reclaim-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: UNKNOWN # enter this manually!